baseurl = "https://www.damuse.dev"
metaDataFormat = "yaml"
title = "Damuse ‚òÄÔ∏èüë©‚Äçüíª"
theme = "blist"
googleAnalytics = "G-L3YWBPBST2"
enableEmoji = true

DefaultContentLanguage = "es"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.es]
    contentDir = "content/es" #Espa√±ol
    weight = 1
    languageName = "Espa√±ol"
    [languages.es.params]
      introTitle = "Hi! Soy Damaris üíï"
      introSubtitle = "Ingeniera de software, que disfruta de la tecnolog√≠a, los juegos de mesa y viajar. Estoy creando este blog para comentar mis experiencias personales y dar algunos tips acerca de mis viajes."
      introPhoto = "/picture.jpg"
      logo = ""
    [[languages.es.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.es.menu.main]]
        name = "Acerca de mi"
        url = "page/about/"
        weight = 2

  
[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = false

  # Custom copyright - optional
  copyright = "Copyright ¬© 2022 - Damaris Avila ¬∑ All rights reserved"
  favicon = "/favicon.ico"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-pink-50"

  # The page bundle that is shown on the front page
  # frontBundle = "blog"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  description = "Me puedes encontrar en las redes sociales :D"
  twitter = "https://twitter.com/Damuseavf"
  linkedin = "https://www.linkedin.com/in/damaris-avila/"
  github = "https://github.com/damuse-avf"
  instagram = "https://www.instagram.com/damuse.avf/"
 
[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true


